[package]
name = "crfsuite"
version = "0.1.0"
authors = ["Messense Lv <messense@icloud.com>"]
description = "Safe wrapper of crfsuite"
license = "MIT"
repository = "https://github.com/bosondata/crfsuite"
keywords = ["crf", "crfsuite"]
readme = "README.md"

[dependencies]
libc = "0.2.35"
crfsuite-sys = { path = "crfsuite-sys", version = "0.1" }

[badges]
travis-ci = { repository = "bosondata/crfsuite-rs" }
