[package]
name = "crfsuite-sys"
version = "0.1.2"
authors = ["Messense Lv <messense@icloud.com>"]
description = "Rust binding to crfsuite"
license = "MIT"
repository = "https://github.com/bosondata/crfsuite"
categories = ["external-ffi-bindings"]
keywords = ["crf", "crfsuite"]
build = "build.rs"
links = "crfsuite"

[dependencies]
libc = "0.2.35"

[build-dependencies]
cc = "1.0.3"
cmake = "0.1.29"

[badges]
travis-ci = { repository = "bosondata/crfsuite-rs" }
